"""add user + service_requests

Revision ID: 0a914bf1061a
Revises: 680d35439c08
Create Date: 2025-08-11 21:44:08.964568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a914bf1061a'
down_revision = '680d35439c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_categories')
    with op.batch_alter_table('worker_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_worker_profiles_city')
        batch_op.drop_index('ix_worker_profiles_full_name')

    op.drop_table('worker_profiles')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_client_id')
        batch_op.drop_index('ix_reviews_worker_id')

    op.drop_table('reviews')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_from_user')
        batch_op.drop_index('ix_messages_request_id')
        batch_op.drop_index('ix_messages_to_user')

    op.drop_table('messages')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_name_key', type_='unique')
        batch_op.drop_index('ix_categories_slug')
        batch_op.drop_column('name')
        batch_op.drop_column('created_at')
        batch_op.drop_column('slug')

    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('client_profiles_user_id_key', type_='unique')
        batch_op.drop_index('ix_client_profiles_city')
        batch_op.drop_constraint('client_profiles_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('lon')
        batch_op.drop_column('created_at')
        batch_op.drop_column('city')
        batch_op.drop_column('user_id')
        batch_op.drop_column('lat')
        batch_op.drop_column('full_name')
        batch_op.drop_column('phone')

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_service_requests_category_id')
        batch_op.drop_index('ix_service_requests_city')
        batch_op.drop_index('ix_service_requests_client_id')
        batch_op.drop_index('ix_service_requests_worker_id')
        batch_op.drop_constraint('service_requests_worker_id_fkey', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('description')
        batch_op.drop_column('city')
        batch_op.drop_column('scheduled_at')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_index('ix_users_email')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('service_requests_worker_id_fkey', 'worker_profiles', ['worker_id'], ['id'])
        batch_op.create_index('ix_service_requests_worker_id', ['worker_id'], unique=False)
        batch_op.create_index('ix_service_requests_client_id', ['client_id'], unique=False)
        batch_op.create_index('ix_service_requests_city', ['city'], unique=False)
        batch_op.create_index('ix_service_requests_category_id', ['category_id'], unique=False)

    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('client_profiles_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_index('ix_client_profiles_city', ['city'], unique=False)
        batch_op.create_unique_constraint('client_profiles_user_id_key', ['user_id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_index('ix_categories_slug', ['slug'], unique=True)
        batch_op.create_unique_constraint('categories_name_key', ['name'])

    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], name='messages_from_user_fkey'),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name='messages_request_id_fkey'),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], name='messages_to_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_to_user', ['to_user'], unique=False)
        batch_op.create_index('ix_messages_request_id', ['request_id'], unique=False)
        batch_op.create_index('ix_messages_from_user', ['from_user'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], name='reviews_client_id_fkey'),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name='reviews_request_id_fkey'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], name='reviews_worker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey'),
    sa.UniqueConstraint('request_id', name='reviews_request_id_key')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_worker_id', ['worker_id'], unique=False)
        batch_op.create_index('ix_reviews_client_id', ['client_id'], unique=False)

    op.create_table('worker_profiles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('worker_profiles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='worker_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='worker_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='worker_profiles_user_id_key'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('worker_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_worker_profiles_full_name', ['full_name'], unique=False)
        batch_op.create_index('ix_worker_profiles_city', ['city'], unique=False)

    op.create_table('worker_categories',
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='worker_categories_category_id_fkey'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], name='worker_categories_worker_id_fkey'),
    sa.PrimaryKeyConstraint('worker_id', 'category_id', name='uq_worker_category')
    )
    # ### end Alembic commands ###
